# Generated by Django 3.0.8 on 2021-11-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myeloma', '0002_auto_20211115_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_folder',
        ),
    ]
