# Generated by Django 3.0.8 on 2021-11-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myeloma', '0003_delete_new_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
    ]
